get_property(_bl_in_try_compile GLOBAL PROPERTY IN_TRY_COMPILE)
if(_bl_in_try_compile)
  return()
endif()

if(BITLOOP_DISCOVERY)
	include("${CMAKE_CURRENT_LIST_DIR}/toolchain/discovery_shims.cmake")
else()
	if(NOT TARGET bitloop::bitloop)
    find_package(bitloop CONFIG REQUIRED)
  endif()
endif()